<?php
/**
 * Quill.php
 *
 * PHP version 7.4+
 *
 * @author Philippe Gaultier <pgaultier@redcat.io>
 * @copyright 2010-2022 Redcat
 * @license https://www.redcat.io/license license
 * @version XXX
 * @link https://www.redcat.io
 * @package blackcube\core\web\helpers
 */
namespace blackcube\core\web\helpers;


/**
 * This is class allow html generated by quill to be cleaned up
 *
 * @author Philippe Gaultier <pgaultier@redcat.io>
 * @copyright 2010-2022 Redcat
 * @license https://www.redcat.io/license license
 * @version XXX
 * @link https://www.redcat.io
 * @package blackcube\core\web\helpers
 * @since XXX
 */
class Quill
{
    /**
     * @param string|null $htmlContent
     * @param array $keepTags list of tags to keep default to ['p'] needed for aria
     * @return string|null
     */
    public static function toRaw($htmlContent, $keepTags = ['p'])
    {
        if ($htmlContent !== null) {
            $cleanHtml = self::cleanHtml($htmlContent);
            $cleanHtml = strip_tags($cleanHtml, $keepTags);
            return $cleanHtml;
        } else {
            return $htmlContent;
        }
    }

    /**
     * Remove style in tags, empty tags, span tags
     *
     * @param string|null $htmlContent
     * @param bool $removeStyles remove styling
     * @param bool $removeEmptyTags remove empty tags
     * @param bool $removeSpan remove spans but keep content
     * @return string|null
     */
    public static function cleanHtml($htmlContent, $removeStyles = true, $removeEmptyTags = true, $removeSpan = true, $addNoFollow = true)
    {
        if ($htmlContent !== null) {
            $cleanHtml = $htmlContent;
            if ($removeStyles === true) {
                $cleanHtml = preg_replace('/style="([^"])*"/', '', $cleanHtml);
            }
            if ($removeEmptyTags === true) {
                $cleanHtml = preg_replace('/<([\S]+)([^>]*)>[\s|&nbsp;|<br(\s|\/)*>]*<\/\1>/', '', $cleanHtml);
            }
            if ($removeSpan === true) {
                $cleanHtml = preg_replace('/<span[^>]*>([^<]*)<\/span>/', '${1}', $cleanHtml);
            }
            if ($addNoFollow === true) {
                $selfBaseUrl = \Yii::$app->request->getHostInfo();
                $cleanHtml = preg_replace_callback('/<a([^>]*)href="(https?:\/\/[^"]+)"([^>]*)>([^<]*)<\/a>/', function ($matches) use ($selfBaseUrl) {
                    if (strncmp($matches[2], $selfBaseUrl, strlen($selfBaseUrl)) === 0) {
                        return $matches[0];
                    } else {
                        $link = $matches[0];
                        if (preg_match('/rel="([^"]*)"/', $link, $relMatches)) {
                            $link = preg_replace('/rel="([^"]*)"/', 'rel="nofollow '.$relMatches[1].'"', $link);
                        } else {
                            $link = preg_replace('/<a([^<]*)>([^<]*)<\/a>/', '<a$1 rel="nofollow">$2</a>', $link);
                        }
                        return $link;
                    }
                }, $cleanHtml);
            }
            return $cleanHtml;
        } else {
            return $htmlContent;
        }

    }
}