<?php
/**
 * m000000_000000_languages.php
 *
 * PHP version 7.2+
 *
 * @author Philippe Gaultier <pgaultier@redcat.io>
 * @copyright 2010-2019 Redcat
 * @license https://www.redcat.io/license license
 * @version XXX
 * @link https://www.redcat.io
 * @package blackcube\core\migrations
 */

namespace blackcube\core\migrations;

use yii\db\Expression;
use yii\db\Migration;

/**
 * Class m000000_000000_languages
 *
 * @author Philippe Gaultier <pgaultier@redcat.io>
 * @copyright 2010-2019 Redcat
 * @license https://www.redcat.io/license license
 * @version XXX
 * @link https://www.redcat.io
 * @package blackcube\core\migrations
 */
class m000000_000000_languages extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%languages}}', [
            'id' => $this->string(6),
            'name' => $this->string(128)->notNull(),
            'main' => $this->boolean()->notNull(),
            'active' => $this->boolean()->defaultValue(true)->notNull(),
            'dateCreate' => $this->dateTime()->notNull(),
            'dateUpdate' => $this->dateTime(),
            'PRIMARY KEY([[id]])'
        ]);
        $this->batchInsert('{{%languages}}', [
            'id',
            'main',
            'name',
            'dateCreate',
            'dateUpdate'
        ], [
            ['af', true,'Afrikaans', new Expression('NOW()'), new Expression('NOW()')],
            ['af-ZA', false,'Afrikaans (South Africa)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar', true,'Arabic', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-AE', false,'Arabic (U.A.E.)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-BH', false,'Arabic (Bahrain)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-DZ', false,'Arabic (Algeria)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-EG', false,'Arabic (Egypt)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-IQ', false,'Arabic (Iraq)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-JO', false,'Arabic (Jordan)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-KW', false,'Arabic (Kuwait)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-LB', false,'Arabic (Lebanon)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-LY', false,'Arabic (Libya)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-MA', false,'Arabic (Morocco)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-OM', false,'Arabic (Oman)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-QA', false,'Arabic (Qatar)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-SA', false,'Arabic (Saudi Arabia)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-SY', false,'Arabic (Syria)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-TN', false,'Arabic (Tunisia)', new Expression('NOW()'), new Expression('NOW()')],
            ['ar-YE', false,'Arabic (Yemen)', new Expression('NOW()'), new Expression('NOW()')],
            ['az', true,'Azeri', new Expression('NOW()'), new Expression('NOW()')],
            ['az-AZ', false,'Azeri (Azerbaijan)', new Expression('NOW()'), new Expression('NOW()')],
            ['be', true,'Belarusian', new Expression('NOW()'), new Expression('NOW()')],
            ['be-BY', false,'Belarusian (Belarus)', new Expression('NOW()'), new Expression('NOW()')],
            ['bg', true,'Bulgarian', new Expression('NOW()'), new Expression('NOW()')],
            ['bg-BG', false,'Bulgarian (Bulgaria)', new Expression('NOW()'), new Expression('NOW()')],
            ['bs-BA', false,'Bosnian (Bosnia and Herzegovina)', new Expression('NOW()'), new Expression('NOW()')],
            ['ca', true,'Catalan', new Expression('NOW()'), new Expression('NOW()')],
            ['ca-ES', false,'Catalan (Spain)', new Expression('NOW()'), new Expression('NOW()')],
            ['cs', true,'Czech', new Expression('NOW()'), new Expression('NOW()')],
            ['cs-CZ', false,'Czech (Czech Republic)', new Expression('NOW()'), new Expression('NOW()')],
            ['cy', true,'Welsh', new Expression('NOW()'), new Expression('NOW()')],
            ['cy-GB', false,'Welsh (United Kingdom)', new Expression('NOW()'), new Expression('NOW()')],
            ['da', true,'Danish', new Expression('NOW()'), new Expression('NOW()')],
            ['da-DK', false,'Danish (Denmark)', new Expression('NOW()'), new Expression('NOW()')],
            ['de', true,'German', new Expression('NOW()'), new Expression('NOW()')],
            ['de-AT', false,'German (Austria)', new Expression('NOW()'), new Expression('NOW()')],
            ['de-CH', false,'German (Switzerland)', new Expression('NOW()'), new Expression('NOW()')],
            ['de-DE', false,'German (Germany)', new Expression('NOW()'), new Expression('NOW()')],
            ['de-LI', false,'German (Liechtenstein)', new Expression('NOW()'), new Expression('NOW()')],
            ['de-LU', false,'German (Luxembourg)', new Expression('NOW()'), new Expression('NOW()')],
            ['dv', true,'Divehi', new Expression('NOW()'), new Expression('NOW()')],
            ['dv-MV', false,'Divehi (Maldives)', new Expression('NOW()'), new Expression('NOW()')],
            ['el', true,'Greek', new Expression('NOW()'), new Expression('NOW()')],
            ['el-GR', false,'Greek (Greece)', new Expression('NOW()'), new Expression('NOW()')],
            ['en', true,'English', new Expression('NOW()'), new Expression('NOW()')],
            ['en-AU', false,'English (Australia)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-BZ', false,'English (Belize)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-CA', false,'English (Canada)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-CB', false,'English (Caribbean)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-GB', false,'English (United Kingdom)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-IE', false,'English (Ireland)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-JM', false,'English (Jamaica)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-NZ', false,'English (New Zealand)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-PH', false,'English (Republic of the Philippines)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-TT', false,'English (Trinidad and Tobago)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-US', false,'English (United States)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-ZA', false,'English (South Africa)', new Expression('NOW()'), new Expression('NOW()')],
            ['en-ZW', false,'English (Zimbabwe)', new Expression('NOW()'), new Expression('NOW()')],
            ['eo', true,'Esperanto', new Expression('NOW()'), new Expression('NOW()')],
            ['es', true,'Spanish', new Expression('NOW()'), new Expression('NOW()')],
            ['es-AR', false,'Spanish (Argentina)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-BO', false,'Spanish (Bolivia)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-CL', false,'Spanish (Chile)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-CO', false,'Spanish (Colombia)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-CR', false,'Spanish (Costa Rica)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-DO', false,'Spanish (Dominican Republic)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-EC', false,'Spanish (Ecuador)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-ES', false,'Spanish (Spain)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-GT', false,'Spanish (Guatemala)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-HN', false,'Spanish (Honduras)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-MX', false,'Spanish (Mexico)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-NI', false,'Spanish (Nicaragua)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-PA', false,'Spanish (Panama)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-PE', false,'Spanish (Peru)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-PR', false,'Spanish (Puerto Rico)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-PY', false,'Spanish (Paraguay)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-SV', false,'Spanish (El Salvador)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-UY', false,'Spanish (Uruguay)', new Expression('NOW()'), new Expression('NOW()')],
            ['es-VE', false,'Spanish (Venezuela)', new Expression('NOW()'), new Expression('NOW()')],
            ['et', true,'Estonian', new Expression('NOW()'), new Expression('NOW()')],
            ['et-EE', false,'Estonian (Estonia)', new Expression('NOW()'), new Expression('NOW()')],
            ['eu', true,'Basque', new Expression('NOW()'), new Expression('NOW()')],
            ['eu-ES', false,'Basque (Spain)', new Expression('NOW()'), new Expression('NOW()')],
            ['fa', true,'Farsi', new Expression('NOW()'), new Expression('NOW()')],
            ['fa-IR', false,'Farsi (Iran)', new Expression('NOW()'), new Expression('NOW()')],
            ['fi', true,'Finnish', new Expression('NOW()'), new Expression('NOW()')],
            ['fi-FI', false,'Finnish (Finland)', new Expression('NOW()'), new Expression('NOW()')],
            ['fo', true,'Faroese', new Expression('NOW()'), new Expression('NOW()')],
            ['fo-FO', false,'Faroese (Faroe Islands)', new Expression('NOW()'), new Expression('NOW()')],
            ['fr', true,'French', new Expression('NOW()'), new Expression('NOW()')],
            ['fr-BE', false,'French (Belgium)', new Expression('NOW()'), new Expression('NOW()')],
            ['fr-CA', false,'French (Canada)', new Expression('NOW()'), new Expression('NOW()')],
            ['fr-CH', false,'French (Switzerland)', new Expression('NOW()'), new Expression('NOW()')],
            ['fr-FR', false,'French (France)', new Expression('NOW()'), new Expression('NOW()')],
            ['fr-LU', false,'French (Luxembourg)', new Expression('NOW()'), new Expression('NOW()')],
            ['fr-MC', false,'French (Principality of Monaco)', new Expression('NOW()'), new Expression('NOW()')],
            ['gl', true,'Galician', new Expression('NOW()'), new Expression('NOW()')],
            ['gl-ES', false,'Galician (Spain)', new Expression('NOW()'), new Expression('NOW()')],
            ['gu', true,'Gujarati', new Expression('NOW()'), new Expression('NOW()')],
            ['gu-IN', false,'Gujarati (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['he', true,'Hebrew', new Expression('NOW()'), new Expression('NOW()')],
            ['he-IL', false,'Hebrew (Israel)', new Expression('NOW()'), new Expression('NOW()')],
            ['hi', true,'Hindi', new Expression('NOW()'), new Expression('NOW()')],
            ['hi-IN', false,'Hindi (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['hr', true,'Croatian', new Expression('NOW()'), new Expression('NOW()')],
            ['hr-BA', false,'Croatian (Bosnia and Herzegovina)', new Expression('NOW()'), new Expression('NOW()')],
            ['hr-HR', false,'Croatian (Croatia)', new Expression('NOW()'), new Expression('NOW()')],
            ['hu', true,'Hungarian', new Expression('NOW()'), new Expression('NOW()')],
            ['hu-HU', false,'Hungarian (Hungary)', new Expression('NOW()'), new Expression('NOW()')],
            ['hy', true,'Armenian', new Expression('NOW()'), new Expression('NOW()')],
            ['hy-AM', false,'Armenian (Armenia)', new Expression('NOW()'), new Expression('NOW()')],
            ['id', true,'Indonesian', new Expression('NOW()'), new Expression('NOW()')],
            ['id-ID', false,'Indonesian (Indonesia)', new Expression('NOW()'), new Expression('NOW()')],
            ['is', true,'Icelandic', new Expression('NOW()'), new Expression('NOW()')],
            ['is-IS', false,'Icelandic (Iceland)', new Expression('NOW()'), new Expression('NOW()')],
            ['it', true,'Italian', new Expression('NOW()'), new Expression('NOW()')],
            ['it-CH', false,'Italian (Switzerland)', new Expression('NOW()'), new Expression('NOW()')],
            ['it-IT', false,'Italian (Italy)', new Expression('NOW()'), new Expression('NOW()')],
            ['ja', true,'Japanese', new Expression('NOW()'), new Expression('NOW()')],
            ['ja-JP', false,'Japanese (Japan)', new Expression('NOW()'), new Expression('NOW()')],
            ['ka', true,'Georgian', new Expression('NOW()'), new Expression('NOW()')],
            ['ka-GE', false,'Georgian (Georgia)', new Expression('NOW()'), new Expression('NOW()')],
            ['kk', true,'Kazakh', new Expression('NOW()'), new Expression('NOW()')],
            ['kk-KZ', false,'Kazakh (Kazakhstan)', new Expression('NOW()'), new Expression('NOW()')],
            ['kn', true,'Kannada', new Expression('NOW()'), new Expression('NOW()')],
            ['kn-IN', false,'Kannada (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['ko', true,'Korean', new Expression('NOW()'), new Expression('NOW()')],
            ['ko-KR', false,'Korean (Korea)', new Expression('NOW()'), new Expression('NOW()')],
            ['kok', true,'Konkani', new Expression('NOW()'), new Expression('NOW()')],
            ['kok-IN', false,'Konkani (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['ky', true,'Kyrgyz', new Expression('NOW()'), new Expression('NOW()')],
            ['ky-KG', false,'Kyrgyz (Kyrgyzstan)', new Expression('NOW()'), new Expression('NOW()')],
            ['lt', true,'Lithuanian', new Expression('NOW()'), new Expression('NOW()')],
            ['lt-LT', false,'Lithuanian (Lithuania)', new Expression('NOW()'), new Expression('NOW()')],
            ['lv', true,'Latvian', new Expression('NOW()'), new Expression('NOW()')],
            ['lv-LV', false,'Latvian (Latvia)', new Expression('NOW()'), new Expression('NOW()')],
            ['mi', true,'Maori', new Expression('NOW()'), new Expression('NOW()')],
            ['mi-NZ', false,'Maori (New Zealand)', new Expression('NOW()'), new Expression('NOW()')],
            ['mk', true,'FYRO Macedonian', new Expression('NOW()'), new Expression('NOW()')],
            ['mk-MK', false,'FYRO Macedonian (Former Yugoslav Republic of Macedonia)', new Expression('NOW()'), new Expression('NOW()')],
            ['mn', true,'Mongolian', new Expression('NOW()'), new Expression('NOW()')],
            ['mn-MN', false,'Mongolian (Mongolia)', new Expression('NOW()'), new Expression('NOW()')],
            ['mr', true,'Marathi', new Expression('NOW()'), new Expression('NOW()')],
            ['mr-IN', false,'Marathi (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['ms', true,'Malay', new Expression('NOW()'), new Expression('NOW()')],
            ['ms-BN', false,'Malay (Brunei Darussalam)', new Expression('NOW()'), new Expression('NOW()')],
            ['ms-MY', false,'Malay (Malaysia)', new Expression('NOW()'), new Expression('NOW()')],
            ['mt', true,'Maltese', new Expression('NOW()'), new Expression('NOW()')],
            ['mt-MT', false,'Maltese (Malta)', new Expression('NOW()'), new Expression('NOW()')],
            ['nb', true,'Norwegian (Bokm?l)', new Expression('NOW()'), new Expression('NOW()')],
            ['nb-NO', false,'Norwegian (Bokm?l) (Norway)', new Expression('NOW()'), new Expression('NOW()')],
            ['nl', true,'Dutch', new Expression('NOW()'), new Expression('NOW()')],
            ['nl-BE', false,'Dutch (Belgium)', new Expression('NOW()'), new Expression('NOW()')],
            ['nl-NL', false,'Dutch (Netherlands)', new Expression('NOW()'), new Expression('NOW()')],
            ['nn-NO', false,'Norwegian (Nynorsk) (Norway)', new Expression('NOW()'), new Expression('NOW()')],
            ['ns', true,'Northern Sotho', new Expression('NOW()'), new Expression('NOW()')],
            ['ns-ZA', false,'Northern Sotho (South Africa)', new Expression('NOW()'), new Expression('NOW()')],
            ['pa', true,'Punjabi', new Expression('NOW()'), new Expression('NOW()')],
            ['pa-IN', false,'Punjabi (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['pl', true,'Polish', new Expression('NOW()'), new Expression('NOW()')],
            ['pl-PL', false,'Polish (Poland)', new Expression('NOW()'), new Expression('NOW()')],
            ['ps', true,'Pashto', new Expression('NOW()'), new Expression('NOW()')],
            ['ps-AR', false,'Pashto (Afghanistan)', new Expression('NOW()'), new Expression('NOW()')],
            ['pt', true,'Portuguese', new Expression('NOW()'), new Expression('NOW()')],
            ['pt-BR', false,'Portuguese (Brazil)', new Expression('NOW()'), new Expression('NOW()')],
            ['pt-PT', false,'Portuguese (Portugal)', new Expression('NOW()'), new Expression('NOW()')],
            ['qu', true,'Quechua', new Expression('NOW()'), new Expression('NOW()')],
            ['qu-BO', false,'Quechua (Bolivia)', new Expression('NOW()'), new Expression('NOW()')],
            ['qu-EC', false,'Quechua (Ecuador)', new Expression('NOW()'), new Expression('NOW()')],
            ['qu-PE', false,'Quechua (Peru)', new Expression('NOW()'), new Expression('NOW()')],
            ['ro', true,'Romanian', new Expression('NOW()'), new Expression('NOW()')],
            ['ro-RO', false,'Romanian (Romania)', new Expression('NOW()'), new Expression('NOW()')],
            ['ru', true,'Russian', new Expression('NOW()'), new Expression('NOW()')],
            ['ru-RU', false,'Russian (Russia)', new Expression('NOW()'), new Expression('NOW()')],
            ['sa', true,'Sanskrit', new Expression('NOW()'), new Expression('NOW()')],
            ['sa-IN', false,'Sanskrit (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['se', true,'Sami (Northern)', new Expression('NOW()'), new Expression('NOW()')],
            ['se-FI', false,'Sami (Finland)', new Expression('NOW()'), new Expression('NOW()')],
            ['se-NO', false,'Sami (Norway)', new Expression('NOW()'), new Expression('NOW()')],
            ['se-SE', false,'Sami (Sweden)', new Expression('NOW()'), new Expression('NOW()')],
            ['sk', true,'Slovak', new Expression('NOW()'), new Expression('NOW()')],
            ['sk-SK', false,'Slovak (Slovakia)', new Expression('NOW()'), new Expression('NOW()')],
            ['sl', true,'Slovenian', new Expression('NOW()'), new Expression('NOW()')],
            ['sl-SI', false,'Slovenian (Slovenia)', new Expression('NOW()'), new Expression('NOW()')],
            ['sq', true,'Albanian', new Expression('NOW()'), new Expression('NOW()')],
            ['sq-AL', false,'Albanian (Albania)', new Expression('NOW()'), new Expression('NOW()')],
            ['sr-BA', false,'Serbian (Bosnia and Herzegovina)', new Expression('NOW()'), new Expression('NOW()')],
            ['sr-SP', false,'Serbian (Serbia and Montenegro)', new Expression('NOW()'), new Expression('NOW()')],
            ['sv', true,'Swedish', new Expression('NOW()'), new Expression('NOW()')],
            ['sv-FI', false,'Swedish (Finland)', new Expression('NOW()'), new Expression('NOW()')],
            ['sv-SE', false,'Swedish (Sweden)', new Expression('NOW()'), new Expression('NOW()')],
            ['sw', true,'Swahili', new Expression('NOW()'), new Expression('NOW()')],
            ['sw-KE', false,'Swahili (Kenya)', new Expression('NOW()'), new Expression('NOW()')],
            ['syr', true,'Syriac', new Expression('NOW()'), new Expression('NOW()')],
            ['syr-SY', false,'Syriac (Syria)', new Expression('NOW()'), new Expression('NOW()')],
            ['ta', true,'Tamil', new Expression('NOW()'), new Expression('NOW()')],
            ['ta-IN', false,'Tamil (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['te', true,'Telugu', new Expression('NOW()'), new Expression('NOW()')],
            ['te-IN', false,'Telugu (India)', new Expression('NOW()'), new Expression('NOW()')],
            ['th', true,'Thai', new Expression('NOW()'), new Expression('NOW()')],
            ['th-TH', false,'Thai (Thailand)', new Expression('NOW()'), new Expression('NOW()')],
            ['tl', true,'Tagalog', new Expression('NOW()'), new Expression('NOW()')],
            ['tl-PH', false,'Tagalog (Philippines)', new Expression('NOW()'), new Expression('NOW()')],
            ['tn', true,'Tswana', new Expression('NOW()'), new Expression('NOW()')],
            ['tn-ZA', false,'Tswana (South Africa)', new Expression('NOW()'), new Expression('NOW()')],
            ['tr', true,'Turkish', new Expression('NOW()'), new Expression('NOW()')],
            ['tr-TR', false,'Turkish (Turkey)', new Expression('NOW()'), new Expression('NOW()')],
            ['tt', true,'Tatar', new Expression('NOW()'), new Expression('NOW()')],
            ['tt-RU', false,'Tatar (Russia)', new Expression('NOW()'), new Expression('NOW()')],
            ['ts', true,'Tsonga', new Expression('NOW()'), new Expression('NOW()')],
            ['uk', true,'Ukrainian', new Expression('NOW()'), new Expression('NOW()')],
            ['uk-UA', false,'Ukrainian (Ukraine)', new Expression('NOW()'), new Expression('NOW()')],
            ['ur', true,'Urdu', new Expression('NOW()'), new Expression('NOW()')],
            ['ur-PK', false,'Urdu (Islamic Republic of Pakistan)', new Expression('NOW()'), new Expression('NOW()')],
            ['uz', true,'Uzbek', new Expression('NOW()'), new Expression('NOW()')],
            ['uz-UZ', false,'Uzbek (Uzbekistan)', new Expression('NOW()'), new Expression('NOW()')],
            ['vi', true,'Vietnamese', new Expression('NOW()'), new Expression('NOW()')],
            ['vi-VN', false,'Vietnamese (Viet Nam)', new Expression('NOW()'), new Expression('NOW()')],
            ['xh', true,'Xhosa', new Expression('NOW()'), new Expression('NOW()')],
            ['xh-ZA', false,'Xhosa (South Africa)', new Expression('NOW()'), new Expression('NOW()')],
            ['zh', true,'Chinese', new Expression('NOW()'), new Expression('NOW()')],
            ['zh-CN', false,'Chinese (S)', new Expression('NOW()'), new Expression('NOW()')],
            ['zh-HK', false,'Chinese (Hong Kong)', new Expression('NOW()'), new Expression('NOW()')],
            ['zh-MO', false,'Chinese (Macau)', new Expression('NOW()'), new Expression('NOW()')],
            ['zh-SG', false,'Chinese (Singapore)', new Expression('NOW()'), new Expression('NOW()')],
            ['zh-TW', false,'Chinese (T)', new Expression('NOW()'), new Expression('NOW()')],
            ['zu', true,'Zulu', new Expression('NOW()'), new Expression('NOW()')],
            ['zu-ZA', false,'Zulu (South Africa)', new Expression('NOW()'), new Expression('NOW()')],
        ]);
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%languages}}');
        return true;
    }
}
